{% set name = "trio" %}
{% set version = "0.17.0" %}
{% set sha256 = "e85cf9858e445465dfbb0e3fdf36efe92082d2df87bfe9d62585eedd6e8e9d7d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=18.2.0
    - sortedcontainers
    - async_generator >=1.9
    - contextvars >=2.1  # [py<37]
    - idna
    - outcome
    - sniffio
    - cffi  # [win]

test:
  imports:
    - trio
    - trio._core
    - trio._core.tests
    - trio._core.tests.test_multierror_scripts
    - trio.testing
    - trio.tests

about:
  home: https://github.com/python-trio/trio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An async/await-native I/O library for humans and snake people
  doc_url: https://trio.readthedocs.io/
  dev_url: https://github.com/python-trio/trio
